Add go vet checking in test.

diff --git a/test b/test
--- a/test
+++ b/test
@@ -7,6 +7,7 @@ cur=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 FORMATTABLE="authsrv chord connector match/datanode match/indexnode sdk dispatcher dynamicmq"
 
 FMT=$FORMATTABLE
+TEST=$FORMATTABLE
 
 
 echo "Running tests..."
@@ -25,6 +26,14 @@ cd $cur
 fmtRes=$(gofmt -l $FMT)
 if [ -n "${fmtRes}" ]; then
     echo -e "gofmt checking failed:\n${fmtRes}"
+    exit 255
+fi
+
+
+echo "Checking govet..."
+vetRes=$(go tool vet -printf=false $TEST)
+if [ -n "${vetRes}" ]; then
+    echo -e "govet checking failed:\n${vetRes}"
     exit 255
 fi
 
